### PR TITLE
[FB-4981] MySQL URL and Curl update

### PR DESCRIPTION
**Pull request by mushyy**
**Description of your patch**
Fixes URLS for percona 

**Recommended Release Notes**
Percona url fixes

**Estimated risk**
High - affects MySQL install

**Components involved**
MySQL

**Description of testing done**

* Created fresh environment 
* Selected MySQL version
* Booted solo instance
* Checked chef ran successfully and MySQL was correct
* Booted multiple instances
* Checked chef ran successfully
* Checked MySQL version 

**QA Instructions**

* Repeat of testing

### CODE REVIEW

**Review by pasanchamikara — CHANGES_REQUESTED** [review]
Checked with solo - mysql v8 -> It appears 8.0.18-9 => Pass
Checked with other 2 versions of mysql as both solo and mult-envs -> they give errors.

For multi 5.x environments

```
[0mNoMethodError[0m
-------------[0m
undefined method `<<' for nil:NilClass[0m

[0mCookbook Trace:[0m
---------------[0m
  /etc/chef/recipes/cookbooks/mysql/recipes/install.rb:78:in `from_file'
[0m  /etc/chef/recipes/cookbooks/mysql/recipes/master.rb:6:in `from_file'
[0m  /etc/chef/recipes/cookbooks/db_master/recipes/prep.rb:7:in `from_file'
[0m  /etc/chef/recipes/cookbooks/ey-init/recipes/main.rb:9:in `block in from_file'
[0m  /etc/chef/recipes/cookbooks/ey-init/recipes/main.rb:9:in `each'
[0m  /etc/chef/recipes/cookbooks/ey-init/recipes/main.rb:9:in `from_file'[0m

[0mRelevant File Content:[0m
----------------------[0m
/etc/chef/recipes/cookbooks/mysql/recipes/install.rb:
[0m
[0m 71:      source "mysql_override.conf"
[0m 72:      owner "root"
[0m 73:      group "root"
[0m 74:      mode 0644
[0m 75:      notifies :run, "execute[reload-systemd]", :immediately
[0m 76:    end
[0m 77:  
[0m 78>>   packages << 'percona-server-server'
[0m 79:  end
[0m 80:  
[0m 81:  ruby_block "install mysql using version on lock file if present" do
[0m 82:    block do
[0m 83:      # check if the version is valid
[0m 84:      if File.exists?(lock_version_file)
[0m 85:        install_version  = %x{cat #{lock_version_file}}.strip
[0m 86:      else
[0m 87:        install_version = node['mysql']['latest_version']
[0m
[0mSystem Info:[0m
```

For solo 5.x

```
ls: cannot access '/var/log/engineyard/apps/': No such file or directory
ls: cannot access '/var/log/engineyard/apps/': No such file or directory
sh: 1: cd: can't cd to /data/nginx/servers
Setting up better bash prompt for user: deploy ...
Found home directory /home/deploy for deploy ...
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Unsupported file /tmp/src/Percona-Server-5.6.47/percona-server-common*.deb given on commandline

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Unsupported file /tmp/src/Percona-Server-5.6.47/libperconaserverclient18.1_*.deb given on commandline

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Unsupported file /tmp/src/Percona-Server-5.6.47/percona-server-client*.deb given on commandline

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

W: --force-yes is deprecated, use one of the options starting with --allow instead.
E: Unsupported file /tmp/src/Percona-Server-5.6.47/percona-server-server*.deb given on commandline
[0m
================================================================================[0m
[31mError executing action `run` on resource 'execute[start-mysql]'[0m
================================================================================[0m

[0mErrno::ENOENT[0m
-------------[0m
execute[Guard resource] (dynamically defined) had an error: Errno::ENOENT: No such file or directory - /etc/init.d/mysql[0m

[0mResource Declaration:[0m
---------------------[0m
# In /etc/chef/recipes/cookbooks/mysql/recipes/startup.rb
[0m
[0m 13: execute "start-mysql" do
[0m 14:   sleeptime = 15      # check mysql's status every 15 seconds
[0m 15:   sleeplimit = 7200   # give mysql 2 hours to start (for long recovery operations)
[0m 16: 
[0m 17:   command "/engineyard/bin/mysql_start --password #{node.engineyard.environment['db_admin_password']} --check #{sleeptime} --timeout #{sleeplimit}"
[0m 18: 
[0m 19:   timeout sleeplimit
[0m 20: 
[0m 21:   not_if "/etc/init.d/mysql status"
[0m 22: end
[0m 23: 
[0m
```

**Comment by mushyy** [comment]
Hi @pasanchamikara Thanks for checking I'm unable to recreate. Where these freshly booted instances and volume or from a snapshot? as I've tried both.

**Comment by pasanchamikara** [comment]
> Hi @pasanchamikara Thanks for checking I'm unable to recreate. Where these freshly booted instances and volume or from a snapshot? as I've tried both.

Thanks for letting me know @mushyy . I have now tried the same with labrea and it appears to be working perfectly. However, I tried overlaying and executing which didn't work for me.

In order to clarify on the process I followed,

```
1. I overlayed the recipes
2. i. Tried with `/opt/chef/embedded/bin/chef-solo -j /etc/chef/dna.json -c /etc/chef/solo.rb > /var/log/chef.manual.log 2>&1`
   ii. Tried running the main chef run `i.apply_updates(User.by_email("youraddress@engineyard.com"), :main)`
```

**Review by pasanchamikara — APPROVED** [review]

**Comment by superflit** [comment]
Msyql56 -> mono Env -> ok
Msyql56 -> multi Env -> ok

**Pull request merged**
